# Generated by Django 5.2 on 2025-05-03 22:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_alter_maps_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
