# Generated by Django 5.2 on 2025-05-03 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_alter_maps_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maps',
            old_name='file',
            new_name='map',
        ),
    ]
