# Generated by Django 5.2 on 2025-05-08 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_invite_status_joinrequest'),
        ('maps', '0004_rename_file_maps_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='campaigns.campaigns'),
            preserve_default=False,
        ),
    ]
