services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rpgworldcompendium
    ports: 
      - 5444:5444

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
